spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ??
    show-sql: true      # ??? SQL ?? ??
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
